name: CI-CD

on:
  push:
    branches: [ "liya" ]
  workflow_dispatch: {}   # запуск из UI вручную

jobs:
  build-and-push:
    name: Build Docker image and push
    runs-on: ubuntu-latest      # GitHub-hosted runner, тут уже есть docker

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cafe-app:latest

  deploy:
    name: Deploy to local Kubernetes
    runs-on: self-hosted        # твой runner в VM
    needs: build-and-push       # запускается ТОЛЬКО после успешного build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Apply Kubernetes manifests
        env:
          KUBECONFIG: /etc/kubernetes/admin.conf   # или твой путь к kubeconfig
        run: |
          kubectl apply -f k8s/namespace.yaml
          kubectl apply -f k8s/postgres-deployment.yaml
          kubectl apply -f k8s/django-deployment.yaml
          kubectl apply -f k8s/ingress.yaml

      - name: Restart Django deployment
        env:
          KUBECONFIG: /etc/kubernetes/admin.conf
        run: |
          kubectl -n cafe rollout restart deployment django
          kubectl -n cafe rollout status deployment django

